version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "php"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "test-coverage"